import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

# sender email address
sender_address = 'alexandra.ciobotaru@fpse.unibuc.ro'

# sender email passowrd for login purposes
sender_pass = '16 characters token generated by gmail'

# list of receivers
li = [("FIRST NAME", 'firnast_name_last_name@gmail.com', 20), ("FIRST NAME 2", 'firnast_name_last_name2@gmail.com', 19)]

# Here we iterate the loop and send msg one by one to the reciver
for i in range(len(li)):
    X = li[i] # this is a tuple from li
    receiver_name = X[0]
    reciver_mail = X[1]
    receiver_grade = X[2]

    print(reciver_mail)

    message = MIMEMultipart()
    message['From'] = sender_address
    message['To'] = reciver_mail  # Pass Reciver Mail Address
    message['Subject'] = 'Seminar Grade at Basic Programming'  # The subject line

    mail_content = '''Hello, {name},
    
Your grade at the Basic Programming seminar is {grade} points. 
    
If you have any questions, please reply to this e-mail.
    
Kind regards,    
Alexandra Ciobotaru'''.format(name = receiver_name.title(), grade = receiver_grade)

    s = smtplib.SMTP('smtp.gmail.com', 587)
    s.starttls()
    s.login(sender_address, sender_pass)
    text = message.as_string()
    s.sendmail(sender_address, reciver_mail, text)
    s.quit()

    print('Mail Sent')

